# Site settings
name: Chegn's blog
email: zolcnb@qq.com
author: Chegn
url: https://chegn7.github.io/blog/
#github: https://github.com/luoyan35714/
#baseurl: "/LessOrMore"
#description: Actually, less is more!
#meta_description: 康志华;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
#motto: It's our wits that make us men.
#banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: chegn7

# Build settings
markdown: kramdown

baidu_analysis: fdd59dfe924f57bdadecd9befbed34d5